### PR TITLE
Editorial: clean up example a bit

### PR DESCRIPTION
**Pull request by marcoscaceres**
Make example a bit more JS idiomatic... and less C++ looking ;)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
When viewed in the spec, this example currently is too large and doesn't fit well. It also looks like it was written to follow C++ coding conventions. I've modernized it a little bit so it fits better. We could remove a bunch of the example HTML too to improve it further.

**Comment by philipwalton** [comment]
Any idea why the travis build is failing here?

**Comment by marcoscaceres** [comment]
It's failing because Travis has nothing to do (it's looking for a "rake file"), so it's just failing.

It should have .travis.yml file, like the other repos.

**Comment by marcoscaceres** [comment]
Was still not super happy with the example. I think this is more reflective of reality (at least, how I've used the API in practice in ReSpec... see "About ReSpec" in the ReSpec pill).

**Comment by siusin** [comment]
Thank you @marcoscaceres ! I suggest a review for this example from Ilya, Philip or Tim who are looking after this spec now.

The build failed because there was no .travis config in the repo. I've added a .travis.yml file and set up the auto-pub for user-timing-2. Lemme know if there's any problem with the deployment.

**Pull request merged**
