### PR TITLE
Change editors

### PR DESCRIPTION
**Pull request by yoavweiss**
Moving @igrigorik to former editors..

***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/user-timing/pull/78.html" title="Last updated on Mar 8, 2021, 10:12 PM UTC (070626f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/user-timing/78/f1cc70d...yoavweiss:070626f.html" title="Last updated on Mar 8, 2021, 10:12 PM UTC (070626f)">Diff</a>

### CODE REVIEW

**Review by npm1 — COMMENTED** [review]
Why are we changing all the lines? Can we restrict the change to the title of this PR?

**Comment by yoavweiss** [comment]
> Why are we changing all the lines? Can we restrict the change to the title of this PR?

Oh my... Accidental :/

**Comment by yoavweiss** [comment]
> Why are we changing all the lines? Can we restrict the change to the title of this PR?

Fixed!

**Review by npm1 — APPROVED** [review]
lgtm!

**Pull request merged**
