### PR TITLE
Negative measure values are valid

### LINKED ISSUE #2: negative duration values
From https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0049.html
[[
In working on the implementation of the User Timing spec in Gecko, it was
brought up about the potential of durations to return negative values.
Specifically it was unclear from the spec whether things like this should
be allowed:

```js
performance.mark('A');
performance.mark('B');

performance.measure('delta', 'B', 'A');

assert( performance.getEntriesByName('delta')[0].duration < 0 ); // true
```

Chrome allows this interaction, enabling negative duration values for
measures. Is this intended, and if so, should we clarify the spec that
negative durations are allowed for performance measurements specifically?
]]

### PR DESCRIPTION
**Pull request by igrigorik**
Closes #2.

### CODE REVIEW

**Comment by igrigorik** [comment]
@plehegar @toddreifsteck @eliperelman ptal.

**Comment by eliperelman** [comment]
Thanks for the clarification, I approve. :+1:

**Comment by toddreifsteck** [comment]
LGTM

**Comment by toddreifsteck** [comment]
Philippe previously voiced approval on a W3C call. Merging.

**Pull request merged**
